-- MySQL Script generated by MySQL Workbench
-- Wed Jan 16 15:54:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sport_club
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sport_club
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sport_club` DEFAULT CHARACTER SET utf8 ;
USE `sport_club` ;

-- -----------------------------------------------------
-- Table `sport_club`.`types_utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport_club`.`types_utilisateur` (
  `type_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type_role` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sport_club`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport_club`.`utilisateurs` (
  `utilisateur_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `utilisateur_nom` VARCHAR(255) NOT NULL,
  `utilisateur_prenom` VARCHAR(255) NOT NULL,
  `utilisateur_adress` VARCHAR(255) NOT NULL,
  `utilisateur_courriel` VARCHAR(255) NOT NULL,
  `utilisateur_motdepass` VARCHAR(255) NULL,
  `types_utilisateur_fk_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`utilisateur_id`),
  INDEX `fk_utilisateurs_types_utilisateur_idx` (`types_utilisateur_fk_id` ASC),
  CONSTRAINT `fk_utilisateurs_types_utilisateur`
    FOREIGN KEY (`types_utilisateur_fk_id`)
    REFERENCES `sport_club`.`types_utilisateur` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sport_club`.`genres_activite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport_club`.`genres_activite` (
  `genre_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `genre_nom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sport_club`.`activites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport_club`.`activites` (
  `activite_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `activite_nom` VARCHAR(255) NOT NULL,
  `activite_max_inscris` INT UNSIGNED NOT NULL,
  `activite_fk_genre_id` INT UNSIGNED NOT NULL,
  `activite_fk_animateur_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`activite_id`),
  INDEX `fk_activites_genres_activite1_idx` (`activite_fk_genre_id` ASC),
  INDEX `fk_activites_utilisateurs1_idx` (`activite_fk_animateur_id` ASC),
  CONSTRAINT `fk_activites_genres_activite1`
    FOREIGN KEY (`activite_fk_genre_id`)
    REFERENCES `sport_club`.`genres_activite` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activites_utilisateurs1`
    FOREIGN KEY (`activite_fk_animateur_id`)
    REFERENCES `sport_club`.`utilisateurs` (`utilisateur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sport_club`.`inscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport_club`.`inscriptions` (
  `inscription_activite_id` INT UNSIGNED NOT NULL,
  `inscriptions_utilisateur_id` INT UNSIGNED NOT NULL,
  `inscription_mode_paiement` VARCHAR(255) NULL,
  `inscription_validation` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`inscription_activite_id`, `inscriptions_utilisateur_id`),
  INDEX `fk_activites_has_utilisateurs_utilisateurs1_idx` (`inscriptions_utilisateur_id` ASC),
  INDEX `fk_activites_has_utilisateurs_activites1_idx` (`inscription_activite_id` ASC),
  CONSTRAINT `fk_activites_has_utilisateurs_activites1`
    FOREIGN KEY (`inscription_activite_id`)
    REFERENCES `sport_club`.`activites` (`activite_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activites_has_utilisateurs_utilisateurs1`
    FOREIGN KEY (`inscriptions_utilisateur_id`)
    REFERENCES `sport_club`.`utilisateurs` (`utilisateur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sport_club`.`animateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport_club`.`animateurs` (
  `animateur_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `animateur_nom` VARCHAR(255) NOT NULL,
  `animateur_prenom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`animateur_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
